/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/oauth2/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 소셜 로그인
         * @description 카카오, 구글, 네이버 소셜 로그인을 처리합니다. 최초 로그인 시 회원 자동 가입이 진행됩니다.
         */
        post: operations["oauthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 토큰 갱신
         * @description refresh_token으로 새 access_token을 발급합니다.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/store-admin/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 매장 관리자 로그인
         * @description 매장 관리자 전용 이메일 + 비밀번호 로그인입니다.
         */
        post: operations["storeAdminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 정보 조회
         * @description 로그인된 고객의 프로필 정보를 조회합니다.
         */
        get: operations["getMyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 정보 수정
         * @description 이름, 전화번호를 수정합니다.
         */
        patch: operations["updateMyInfo"];
        trace?: never;
    };
    "/users/me/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 이용 매장 등록
         * @description 고객이 이용할 매장을 등록합니다. is_preferred를 true로 설정하면 주로 이용하는 매장으로 지정됩니다.
         */
        post: operations["registerUserStore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 매장 목록 조회
         * @description 전체 활성 매장 목록을 조회합니다.
         */
        get: operations["getStores"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 매장 상세 조회 */
        get: operations["getStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 공구 상품 목록 조회 (진행중)
         * @description 현재 진행 중인(ACTIVE) 공구 상품 목록을 조회합니다.
         */
        get: operations["getProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 공구 상품 상세 조회 */
        get: operations["getProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 공구 상품 등록
         * @description 매장 관리자가 공구 상품을 등록합니다.
         */
        post: operations["createProduct"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/products/{product_id}/arrive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 입고 처리
         * @description 공구 물품 입고 처리 시 주문 상태를 ARRIVED로 일괄 변경하고, 고객에게 알림을 발송합니다.
         */
        put: operations["arriveProduct"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 주문 예약
         * @description 공구 상품을 예약합니다. 선착순으로 재고를 선점하며, 재고 소진 시 즉시 실패합니다.
         */
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 주문 목록 조회
         * @description 로그인된 고객의 주문 목록을 조회합니다.
         */
        get: operations["getMyOrders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 주문 상세 조회 */
        get: operations["getOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 주문 취소
         * @description 주문을 취소합니다. RESERVED 또는 PAID 상태에서만 취소 가능합니다. 결제 완료 건은 PG 자동 취소 처리됩니다.
         */
        post: operations["cancelOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orders/{order_id}/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 수령 완료 처리
         * @description 고객이 물품 수령을 완료합니다. ARRIVED 상태에서만 가능합니다.
         */
        post: operations["receiveOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/prepare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 준비 (2-phase 1단계)
         * @description 2-phase 결제 흐름의 1단계. 서버가 paymentId(UUID)를 생성하고 Payment PENDING 레코드를
         *     선(先) 저장한다. 클라이언트는 반환된 paymentId와 amount를 포트원 SDK에 전달하여 실결제를 진행한다.
         */
        post: operations["preparePayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 결제 검증 및 확정 (2-phase 2단계, 클라이언트 호출)
         * @description 2-phase 결제 흐름의 2단계. 포트원 SDK 결제 완료 후 클라이언트가 호출한다.
         *     서버 측 금액 검증 및 주문 확정을 처리하며, 이미 PAID 상태이면 멱등 응답을 반환한다.
         */
        post: operations["verifyPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * PortOne 결제 웹훅 수신 (2-phase 2단계, PortOne 서버 호출)
         * @description PortOne 서버가 결제 완료 시 호출하는 웹훅 엔드포인트. 인증 불필요(PortOne 서버 발신).
         *     /payments/verify와 동일한 completePayment 서비스를 호출하며 멱등 처리된다.
         */
        post: operations["receivePaymentWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 알림 목록 조회 */
        get: operations["getMyNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 알림 읽음 처리 */
        patch: operations["readNotification"];
        trace?: never;
    };
    "/admin/products/{product_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 현황 조회 — 상품별
         * @description 특정 공구 상품의 전체 주문 현황을 조회합니다.
         */
        get: operations["getOrdersByProduct"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{user_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주문 현황 조회 — 고객별
         * @description 특정 고객의 매장 내 전체 주문 이력을 조회합니다.
         */
        get: operations["getOrdersByUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 고객 목록 조회
         * @description 매장에 등록된 고객 목록을 조회합니다.
         */
        get: operations["getAdminUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description 에러 코드 */
            code?: string;
            errors?: {
                field?: string;
                reason?: string;
            }[];
        };
        PageInfo: {
            page?: number;
            size?: number;
            total_elements?: number;
            total_pages?: number;
        };
        OAuthLoginRequest: {
            /** @enum {string} */
            provider: "KAKAO" | "GOOGLE" | "NAVER";
            /** @description 소셜 플랫폼에서 발급한 고유 ID */
            provider_id: string;
            name: string;
            /** Format: email */
            email?: string;
        };
        LoginResponse: {
            code?: string;
            data?: {
                access_token?: string;
                refresh_token?: string;
                token_type?: string;
                /** @description 만료 시간 (초) */
                expires_in?: number;
                user?: {
                    /** Format: int64 */
                    id?: number;
                    name?: string;
                    /** @enum {string} */
                    role?: "CUSTOMER" | "STORE_ADMIN" | "HQ_ADMIN";
                };
            };
        };
        TokenRefreshRequest: {
            refreshToken: string;
        };
        TokenRefreshResponse: {
            code?: string;
            data?: {
                accessToken?: string;
            };
        };
        StoreAdminLoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        StoreAdminLoginResponse: {
            code?: string;
            data?: {
                accessToken?: string;
                refreshToken?: string;
            };
        };
        UserResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                id?: number;
                name?: string;
                email?: string;
                phone?: string;
                preferred_store?: {
                    /** Format: int64 */
                    id?: number;
                    name?: string;
                };
                connected_providers?: ("KAKAO" | "GOOGLE" | "NAVER")[];
            };
        };
        UpdateUserRequest: {
            name?: string;
            phone?: string;
        };
        UpdateUserResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                id?: number;
                name?: string;
                phone?: string;
            };
        };
        RegisterUserStoreRequest: {
            /** Format: int64 */
            store_id: number;
            /** @default false */
            is_preferred: boolean;
        };
        RegisterUserStoreResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                store_id?: number;
                store_name?: string;
                is_preferred?: boolean;
            };
        };
        StoreListResponse: {
            code?: string;
            data?: {
                content?: components["schemas"]["StoreItem"][];
            } & components["schemas"]["PageInfo"];
        };
        StoreResponse: {
            code?: string;
            data?: components["schemas"]["StoreItem"];
        };
        StoreItem: {
            /** Format: int64 */
            id?: number;
            name?: string;
            address?: string;
            phone?: string;
        };
        ProductListResponse: {
            code?: string;
            data?: {
                content?: components["schemas"]["ProductItem"][];
            } & components["schemas"]["PageInfo"];
        };
        ProductDetailResponse: {
            code?: string;
            data?: components["schemas"]["ProductItem"];
        };
        ProductItem: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            store_id?: number;
            store_name?: string;
            name?: string;
            description?: string;
            /**
             * Format: int64
             * @description 원화 (BIGINT)
             */
            price?: number;
            total_stock?: number;
            remaining_stock?: number;
            /** @enum {string} */
            status?: "UPCOMING" | "ACTIVE" | "SOLD_OUT" | "CLOSED";
            /** Format: date-time */
            start_at?: string;
            /** Format: date-time */
            end_at?: string;
        };
        CreateProductRequest: {
            name: string;
            description?: string;
            /** Format: int64 */
            price: number;
            total_stock: number;
            /** Format: date-time */
            start_at: string;
            /** Format: date-time */
            end_at: string;
        };
        CreateProductResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                id?: number;
                name?: string;
                status?: string;
            };
        };
        ArriveProductResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                product_id?: number;
                notified_count?: number;
                arrived_order_count?: number;
            };
        };
        CreateOrderRequest: {
            /** Format: int64 */
            product_id: number;
            quantity: number;
        };
        CreateOrderResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                order_id?: number;
                /** @enum {string} */
                status?: "RESERVED";
                /** Format: int64 */
                product_id?: number;
                quantity?: number;
                /** Format: int64 */
                total_price?: number;
                /** Format: date-time */
                created_at?: string;
            };
        };
        OrderListResponse: {
            code?: string;
            data?: {
                content?: components["schemas"]["OrderItem"][];
            } & components["schemas"]["PageInfo"];
        };
        OrderItem: {
            /** Format: int64 */
            order_id?: number;
            product_name?: string;
            quantity?: number;
            /** Format: int64 */
            total_price?: number;
            /** @enum {string} */
            status?: "RESERVED" | "PAID" | "ARRIVED" | "RECEIVED" | "CANCELLED";
            /** Format: date-time */
            created_at?: string;
        };
        OrderDetailResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                order_id?: number;
                /** @enum {string} */
                status?: "RESERVED" | "PAID" | "ARRIVED" | "RECEIVED" | "CANCELLED";
                /** Format: int64 */
                total_price?: number;
                items?: {
                    /** Format: int64 */
                    product_id?: number;
                    product_name?: string;
                    quantity?: number;
                    /** Format: int64 */
                    unit_price?: number;
                }[];
                payment?: {
                    imp_uid?: string;
                    /** Format: int64 */
                    amount?: number;
                    /** @enum {string} */
                    status?: "PENDING" | "PAID" | "CANCELLED" | "FAILED";
                    /** Format: date-time */
                    paid_at?: string;
                };
                /** Format: date-time */
                created_at?: string;
            };
        };
        CancelOrderRequest: {
            cancel_reason?: string;
        };
        CancelOrderResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                order_id?: number;
                status?: string;
                /** Format: date-time */
                cancelled_at?: string;
            };
        };
        ReceiveOrderResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                order_id?: number;
                status?: string;
                /** Format: date-time */
                received_at?: string;
            };
        };
        PreparePaymentRequest: {
            /** Format: int64 */
            order_id: number;
        };
        PreparePaymentResponse: {
            code?: string;
            data?: {
                /** @description 서버 생성 UUID (포트원 SDK에 전달) */
                paymentId?: string;
                /** Format: int64 */
                amount?: number;
            };
        };
        VerifyPaymentRequest: {
            /** Format: int64 */
            order_id: number;
            /** @description preparePayment에서 반환된 paymentId */
            payment_id: string;
        };
        VerifyPaymentResponse: {
            code?: string;
            data?: {
                /** Format: int64 */
                orderId?: number;
                paymentId?: string;
                /** Format: int64 */
                amount?: number;
                /** @enum {string} */
                status?: "PAID" | "CANCELLED";
                /** Format: date-time */
                paidAt?: string;
                /** @enum {string} */
                orderStatus?: "PAID" | "CANCELLED";
            };
        };
        PortOneWebhookPayload: {
            /** @example Transaction.Paid */
            type: string;
            data: {
                paymentId: string;
            };
        };
        NotificationListResponse: {
            code?: string;
            data?: {
                content?: {
                    /** Format: int64 */
                    id?: number;
                    /** @enum {string} */
                    type?: "ARRIVED" | "ORDER_CONFIRMED" | "CANCELLED";
                    message?: string;
                    is_read?: boolean;
                    /** Format: date-time */
                    sent_at?: string;
                }[];
                unread_count?: number;
                total_elements?: number;
            };
        };
    };
    responses: {
        /** @description 인증 토큰이 없거나 만료되었습니다. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AUTH_UNAUTHORIZED",
                 *       "errors": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 권한이 없습니다. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "AUTH_FORBIDDEN",
                 *       "errors": []
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 입력값 유효성 검사 실패 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "code": "VALIDATION_FAILED",
                 *       "errors": [
                 *         {
                 *           "field": "fieldName",
                 *           "reason": "에러 사유"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 페이지 번호 (기본값 0) */
        Page: number;
        /** @description 페이지 크기 (기본값 20) */
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    oauthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OAuthLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "AUTH_LOGIN_SUCCESS",
                     *       "data": {
                     *         "access_token": "eyJhbGci...",
                     *         "refresh_token": "eyJhbGci...",
                     *         "token_type": "Bearer",
                     *         "expires_in": 3600,
                     *         "user": {
                     *           "id": 1,
                     *           "name": "홍길동",
                     *           "role": "CUSTOMER"
                     *         }
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 지원하지 않는 소셜 로그인 제공자 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "AUTH_INVALID_PROVIDER",
                     *       "errors": [
                     *         {
                     *           "field": "provider",
                     *           "reason": "지원하지 않는 소셜 로그인 제공자입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 유효성 검사 실패 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description 토큰 갱신 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "AUTH_TOKEN_REFRESHED",
                     *       "data": {
                     *         "accessToken": "eyJhbGci..."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            /** @description 유효하지 않은 refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    storeAdminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreAdminLoginRequest"];
            };
        };
        responses: {
            /** @description 로그인 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "AUTH_LOGIN_SUCCESS",
                     *       "data": {
                     *         "accessToken": "eyJhbGci...",
                     *         "refreshToken": "eyJhbGci..."
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["StoreAdminLoginResponse"];
                };
            };
            /** @description 인증 실패 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "AUTH_INVALID_CREDENTIALS",
                     *       "errors": [
                     *         {
                     *           "field": "email",
                     *           "reason": "이메일 또는 비밀번호가 올바르지 않습니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 비활성화된 계정 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "USER_FOUND",
                     *       "data": {
                     *         "id": 1,
                     *         "name": "홍길동",
                     *         "email": "hong@example.com",
                     *         "phone": "010-1234-5678",
                     *         "preferred_store": {
                     *           "id": 1,
                     *           "name": "소도몰 강남점"
                     *         },
                     *         "connected_providers": [
                     *           "KAKAO",
                     *           "GOOGLE"
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateMyInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 수정 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpdateUserResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    registerUserStore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterUserStoreRequest"];
            };
        };
        responses: {
            /** @description 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "USER_STORE_REGISTERED",
                     *       "data": {
                     *         "store_id": 1,
                     *         "store_name": "소도몰 강남점",
                     *         "is_preferred": true
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["RegisterUserStoreResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 존재하지 않는 매장 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "STORE_NOT_FOUND",
                     *       "errors": [
                     *         {
                     *           "field": "store_id",
                     *           "reason": "존재하지 않는 매장입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 등록된 매장 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "USER_STORE_DUPLICATE",
                     *       "errors": [
                     *         {
                     *           "field": "store_id",
                     *           "reason": "이미 등록된 매장입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getStores: {
        parameters: {
            query?: {
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreListResponse"];
                };
            };
        };
    };
    getStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreResponse"];
                };
            };
            /** @description 존재하지 않는 매장 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "STORE_NOT_FOUND",
                     *       "errors": [
                     *         {
                     *           "field": "store_id",
                     *           "reason": "존재하지 않는 매장입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProducts: {
        parameters: {
            query?: {
                /** @description 매장 ID로 필터링 */
                store_id?: number;
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
        };
    };
    getProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetailResponse"];
                };
            };
            /** @description 존재하지 않는 상품 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PRODUCT_NOT_FOUND",
                     *       "errors": [
                     *         {
                     *           "field": "product_id",
                     *           "reason": "존재하지 않는 상품입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProduct: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description 등록 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PRODUCT_CREATED",
                     *       "data": {
                     *         "id": 1,
                     *         "name": "유기농 사과 5kg",
                     *         "status": "UPCOMING"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["CreateProductResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    arriveProduct: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 입고 처리 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PRODUCT_ARRIVED",
                     *       "data": {
                     *         "product_id": 1,
                     *         "notified_count": 43,
                     *         "arrived_order_count": 43
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ArriveProductResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 존재하지 않는 상품 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 이미 입고 처리된 상품 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PRODUCT_ALREADY_ARRIVED",
                     *       "errors": []
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description 주문 생성 성공 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_CREATED",
                     *       "data": {
                     *         "order_id": 1,
                     *         "status": "RESERVED",
                     *         "product_id": 1,
                     *         "quantity": 2,
                     *         "total_price": 50000,
                     *         "created_at": "2026-03-30T10:00:00"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["CreateOrderResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 존재하지 않는 상품 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 재고 소진 또는 주문 불가 상태 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    getMyOrders: {
        parameters: {
            query?: {
                /** @description 주문 상태 필터 */
                status?: "RESERVED" | "PAID" | "ARRIVED" | "RECEIVED" | "CANCELLED";
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderDetailResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 존재하지 않는 주문 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_NOT_FOUND",
                     *       "errors": [
                     *         {
                     *           "field": "order_id",
                     *           "reason": "존재하지 않는 주문입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cancelOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CancelOrderRequest"];
            };
        };
        responses: {
            /** @description 취소 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_CANCELLED",
                     *       "data": {
                     *         "order_id": 1,
                     *         "status": "CANCELLED",
                     *         "cancelled_at": "2026-03-30T11:00:00"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["CancelOrderResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 존재하지 않는 주문 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 취소 불가 상태 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_CANNOT_CANCEL",
                     *       "errors": [
                     *         {
                     *           "field": null,
                     *           "reason": "취소할 수 없는 주문 상태입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    receiveOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 수령 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_RECEIVED",
                     *       "data": {
                     *         "order_id": 1,
                     *         "status": "RECEIVED",
                     *         "received_at": "2026-04-15T14:00:00"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["ReceiveOrderResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 존재하지 않는 주문 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 입고 전 수령 불가 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ORDER_NOT_ARRIVED",
                     *       "errors": [
                     *         {
                     *           "field": null,
                     *           "reason": "입고 완료된 주문만 수령 처리할 수 있습니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    preparePayment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreparePaymentRequest"];
            };
        };
        responses: {
            /** @description 결제 준비 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "SUCCESS",
                     *       "data": {
                     *         "paymentId": "pay-uuid-001",
                     *         "amount": 50000
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["PreparePaymentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 존재하지 않는 주문 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 소유권 불일치 또는 결제 불가 상태 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verifyPayment: {
        parameters: {
            query?: never;
            header?: {
                /** @description 이중 결제 방지용 멱등성 키 (UUID, 추후 지원 예정) */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyPaymentRequest"];
            };
        };
        responses: {
            /** @description 결제 검증 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "SUCCESS",
                     *       "data": {
                     *         "orderId": 1,
                     *         "paymentId": "pay-uuid-001",
                     *         "amount": 50000,
                     *         "status": "PAID",
                     *         "paidAt": "2026-03-30T10:05:00",
                     *         "orderStatus": "PAID"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["VerifyPaymentResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description 존재하지 않는 결제 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description 결제 금액 불일치 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "PAYMENT_AMOUNT_MISMATCH",
                     *       "errors": [
                     *         {
                     *           "field": null,
                     *           "reason": "결제 금액이 주문 금액과 일치하지 않습니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description PG사 통신 오류 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    receivePaymentWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "type": "Transaction.Paid",
                 *       "data": {
                 *         "paymentId": "pay-uuid-001"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["PortOneWebhookPayload"];
            };
        };
        responses: {
            /** @description 웹훅 처리 완료 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMyNotifications: {
        parameters: {
            query?: {
                /** @description 읽음 여부 필터 (미입력 시 전체) */
                is_read?: boolean;
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "NOTIFICATION_LIST_FOUND",
                     *       "data": {
                     *         "content": [
                     *           {
                     *             "id": 1,
                     *             "type": "ARRIVED",
                     *             "message": "유기농 사과 5kg 물품이 입고되었습니다.",
                     *             "is_read": false,
                     *             "sent_at": "2026-04-10T09:00:00"
                     *           }
                     *         ],
                     *         "unread_count": 1,
                     *         "total_elements": 1
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    readNotification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 읽음 처리 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "NOTIFICATION_READ",
                     *       "data": {
                     *         "id": 1,
                     *         "is_read": true
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description 존재하지 않는 알림 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "NOTIFICATION_NOT_FOUND",
                     *       "errors": [
                     *         {
                     *           "field": "notification_id",
                     *           "reason": "존재하지 않는 알림입니다."
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrdersByProduct: {
        parameters: {
            query?: {
                status?: "RESERVED" | "PAID" | "ARRIVED" | "RECEIVED" | "CANCELLED";
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ADMIN_ORDER_LIST_FOUND",
                     *       "data": {
                     *         "product_id": 1,
                     *         "product_name": "유기농 사과 5kg",
                     *         "total_orders": 43,
                     *         "status_summary": {
                     *           "RESERVED": 5,
                     *           "PAID": 30,
                     *           "ARRIVED": 6,
                     *           "RECEIVED": 2
                     *         },
                     *         "content": [
                     *           {
                     *             "order_id": 1,
                     *             "user_name": "홍길동",
                     *             "user_phone": "010-1234-5678",
                     *             "quantity": 2,
                     *             "total_price": 50000,
                     *             "status": "PAID"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getOrdersByUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ADMIN_USER_ORDER_LIST_FOUND",
                     *       "data": {
                     *         "user_id": 1,
                     *         "user_name": "홍길동",
                     *         "total_orders": 3,
                     *         "content": [
                     *           {
                     *             "order_id": 1,
                     *             "product_name": "유기농 사과 5kg",
                     *             "quantity": 2,
                     *             "total_price": 50000,
                     *             "status": "RECEIVED",
                     *             "created_at": "2026-03-30T10:00:00"
                     *           }
                     *         ]
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getAdminUsers: {
        parameters: {
            query?: {
                /** @description 이름으로 검색 */
                name?: string;
                /** @description 페이지 번호 (기본값 0) */
                page?: components["parameters"]["Page"];
                /** @description 페이지 크기 (기본값 20) */
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 조회 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "code": "ADMIN_USER_LIST_FOUND",
                     *       "data": {
                     *         "content": [
                     *           {
                     *             "user_id": 1,
                     *             "name": "홍길동",
                     *             "phone": "010-1234-5678",
                     *             "order_count": 3,
                     *             "registered_at": "2026-01-15T10:00:00"
                     *           }
                     *         ],
                     *         "total_elements": 1,
                     *         "total_pages": 1
                     *       }
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
