spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      minimum-idle: 25
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

portone:
  base-url: http://gongu-mock-pg:8090

order:
  reservation-ttl-minutes: 5

logging:
  level:
    io.github.resilience4j.circuitbreaker: DEBUG
